spring:
  application:
    name: dehradun-cab-booking
  datasource:
    url: jdbc:postgresql://localhost:5432/dehradun_cabs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

city:
  name: Dehradun
  state: Uttarakhand
  country: India
  timezone: Asia/Kolkata
  supportEmail: support@dooncabs.example
