package com.dehradun.cabbooking.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request payload to register a new rider within the platform.
 */
public class CreateUserRequest {

    @NotBlank
    @Size(max = 100)
    private String name;

    @NotBlank
    @Size(max = 15)
    private String phone;

    @Email
    @Size(max = 100)
    private String email;

    @NotBlank
    @Size(max = 200)
    private String passwordHash;

    /**
     * Provides the display name for the new rider.
     *
     * @return rider name text
     */
    public String getName() {
        return name;
    }

    /**
     * Assigns the display name for the new rider.
     *
     * @param name textual name of the rider
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gives the primary phone number used for login and notifications.
     *
     * @return formatted phone string
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Registers the primary phone number used for login and notifications.
     *
     * @param phone rider contact number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Returns the optional email address of the rider.
     *
     * @return rider email value
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the optional email address of the rider.
     *
     * @param email rider email value
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Exposes the hashed password generated by the client.
     *
     * @return credential hash string
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * Stores the hashed password generated by the client.
     *
     * @param passwordHash credential hash string
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
}
